# site settings
title: Digilocity
subtitle: Creative at Scale
email: contact@creativeplatform.app
description: Helping advertisers produce creative at scale.
baseurl: # the subpath of your site, e.g. /blog
url: digilocity.com # the base hostname & protocol for your site
author: James Knight
street_address: 101 West Street
city: New York
state: NY
zip_code: 10021
country: USA
phone: +16025495339

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
